### ISSUE TITLE
Query doesn't work

### ISSUE THREAD

**Issue by j4zzcat** [newrelic/nr1-status-widgets#27]
Hello,

The following query:
```
select average(aws.rds.CPUUtilization) from Metric where aws.rds.DBInstanceIdentifier = 'data-db-prod' and tags.env = 'prod' 
```
Works perfectly in the platform's query builder, but doesn't seem to work in the status widget.
Maybe it's connected to the "Your Metric query has been transformed into a query that is compatible with the previous Infrastructure metric format."  message?

<img width="2037" alt="Screen Shot 2022-04-07 at 9 42 48" src="https://user-images.githubusercontent.com/178921/162136922-0b890e38-dec5-4bbe-9337-6719ed76e7aa.png">
<img width="1868" alt="Screen Shot 2022-04-07 at 9 44 16" src="https://user-images.githubusercontent.com/178921/162136932-84e32172-2cc1-4dbc-80f3-5c74202056df.png">

**Comment by Kav91** [comment]
I was unable to replicate this issue in my account with the identical query.
Are you able to share if you had any errors in the console, and also any additional configuration you applied for the widget?

**Comment by j4zzcat** [comment]
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'postMessage')
    at t.n._send (one-app-37f8c229.js:1:655117)
    at t.n._send (one-app-37f8c229.js:1:222042)
    at t.<anonymous> (one-app-37f8c229.js:1:654298)
    at a (one-vbp-af9ccb81.js:1:43409)
    at Generator._invoke (one-vbp-af9ccb81.js:1:43197)
    at Generator.next (one-vbp-af9ccb81.js:1:43834)
    at n (one-vbp-af9ccb81.js:1:57414)
    at c (one-vbp-af9ccb81.js:1:57625)
    at one-vbp-af9ccb81.js:1:57684
    at nrWrapper (us-1216.js:1:29912)
```

**Comment by Kav91** [comment]
I am not sure if it could have been to do with one of the releases in-between that time frame of the issue being raised and now that fixed it 🤷🏾 
So I will close this one for now, and if it reappears feel free to re-open 👍🏾
