### ISSUE TITLE
Status Table Widget - 0s show as nulls

### ISSUE THREAD

**Issue by khpeet** [newrelic/nr1-status-widgets#37]
## Description

Status Table Widget - 0s show as nulls. Example:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/11946809/181780142-96ca950f-6fe6-418c-99ea-7515e02283db.png">

## Steps to Reproduce

Deploy Status Table widget - Run query with 0 result returned

## Expected Behaviour

Literal 0 displayed, not null.

**Comment by Kav91** [comment]
Fixed in latest release, value will display now. In cell configuration you can flag on the `trigger if zero` as well for the color/highlighting to function properly.
