### ISSUE TITLE
Match the Red/Yellow/Green colors with those used by NR

### ISSUE THREAD

**Issue by j4zzcat** [newrelic/nr1-status-widgets#41]
New Relic UI uses the following colors to indicate Healthy, Warning and Critical status, it would be nice to match this color scheme.
Red - #a1251a
Yellow - #f8d45c
Green - #3a845e
<img width="986" alt="Screen Shot 2022-11-28 at 22 34 46" src="https://user-images.githubusercontent.com/178921/204375622-d7fa1643-bde1-459c-929c-673353dc7c90.png">

**Comment by Kav91** [comment]
resolved in #42
