### ISSUE TITLE
Values are not being re-render when default time is changed using time Picker option in the dashboard

### ISSUE THREAD

**Issue by Omared250** [newrelic/nr1-status-widgets#57]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I have created a widget using the NRQL status widget option, one of the configurations of this widget is to polling data every 5 seconds and everything is working if the time picker of the dashboard I have attached the widget to, stay with the default option but as long as I change the time picker option to any other value, the data stop the updating process and if you check the network tab under the inspector you will see that the request is happening but the value is not being re-render in the UI.

## Steps to Reproduce

Add Data option -> Look into App & Visualisations -> enable the app Status Widget Pack -> select the option NRQL status Widget -> create a query like SELECT count(*) FROM Transaction -> set some critical and warning thresholds -> set polling to 5 seconds -> save the widget into a dashboard -> open the dashboard and see that the widget is being updating with the values every second in the default option of the time picker -> change dashboard's time picker to 5 minutes -> widget stop the re-render process of the value.

## Expected Behaviour

Change the dashboard's time picker without affecting the re-render process of the widget's value since the polling should keeps happening every 5 seconds

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Browser name and version: Google Chrome Version 121.0.6167.139 (Official Build) (arm64)
* Operating System and version: macOS Sonoma 14.3

**Comment by Kav91** [comment]
This should be fixed in the latest release. Feel free to reopen if the issue persists.

**Comment by Omared250** [comment]
Thank you I will let you know in case the issue persists, really appreciate your help 👍🏽
